[2025-05-21T09:54:08.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T09:54:08.760+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T09:54:08.788+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [queued]>
[2025-05-21T09:54:08.789+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 6
[2025-05-21T09:54:08.825+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): prediction> on 2025-05-21 09:20:57.597132+00:00
[2025-05-21T09:54:08.852+0000] {standard_task_runner.py:72} INFO - Started process 1248 to run task
[2025-05-21T09:54:08.864+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'prediction', 'manual__2025-05-21T09:20:57.597132+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpn1_gj98c']
[2025-05-21T09:54:08.873+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask prediction
[2025-05-21T09:54:08.992+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.prediction manual__2025-05-21T09:20:57.597132+00:00 [running]> on host c735ccec6410
[2025-05-21T09:54:09.176+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:20:57.597132+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:20:57.597132+00:00'
[2025-05-21T09:54:09.179+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T09:54:09.243+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 95, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 35, in predict_contrails
    df=df[self.features] # Align training columns with input data
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Contrails (kgCO2e)', 'Month',\n       'Day', 'Weekday', 'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"
[2025-05-21T09:54:09.286+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=merge_sources_pipeline, task_id=prediction, run_id=manual__2025-05-21T09:20:57.597132+00:00, execution_date=20250521T092057, start_date=20250521T095408, end_date=20250521T095409
[2025-05-21T09:54:09.351+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T09:54:09.352+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 104 for task prediction ("None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Contrails (kgCO2e)', 'Month',\n       'Day', 'Weekday', 'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"; 1248)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 95, in prediction
    result_df = run_inference(preprocessed_df)
  File "/opt/airflow/scripts/inference.py", line 16, in run_inference
    y_pred = predictor.predict_contrails(df_predict)
  File "/opt/airflow/scripts/predictor.py", line 35, in predict_contrails
    df=df[self.features] # Align training columns with input data
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['Aircraft', 'Engine', 'Seats', 'Origin Airport', 'Destination Airport',\n       'Distance Flown (km)', 'CO2 (kgCO2e)', 'Contrails (kgCO2e)', 'Month',\n       'Day', 'Weekday', 'Takeoff_Hour'],\n      dtype='object')] are in the [columns]"
[2025-05-21T09:54:09.404+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-21T09:54:09.457+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T09:54:09.461+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
