[2025-05-21T14:18:20.955+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T14:18:21.123+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T14:18:09.814498+00:00 [queued]>
[2025-05-21T14:18:21.250+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T14:18:09.814498+00:00 [queued]>
[2025-05-21T14:18:21.261+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T14:18:21.460+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_flight_file> on 2025-05-21 14:18:09.814498+00:00
[2025-05-21T14:18:21.582+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-05-21T14:18:21.616+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'contrails_prediction_pipeline', 'wait_for_flight_file', 'manual__2025-05-21T14:18:09.814498+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmp0pmdiaj8']
[2025-05-21T14:18:21.629+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask wait_for_flight_file
[2025-05-21T14:18:22.178+0000] {task_command.py:467} INFO - Running <TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T14:18:09.814498+00:00 [running]> on host 86ce19bc7751
[2025-05-21T14:18:22.706+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='contrails_prediction_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_flight_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T14:18:09.814498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T14:18:09.814498+00:00'
[2025-05-21T14:18:22.713+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T14:18:22.723+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T14:18:22.783+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T14:18:22.785+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/flight_2025_05.csv
[2025-05-21T14:18:22.786+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/flight_2025_05.csv last modified: 20250521100735
[2025-05-21T14:18:22.786+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-05-21T14:18:22.787+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/flight_2025_05.csv
[2025-05-21T14:18:22.787+0000] {filesystem.py:113} INFO - Found File /opt/***/data/raw_data/flight_2025_05.csv last modified: 20250521100735
[2025-05-21T14:18:22.816+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T14:18:22.817+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=contrails_prediction_pipeline, task_id=wait_for_flight_file, run_id=manual__2025-05-21T14:18:09.814498+00:00, execution_date=20250521T141809, start_date=20250521T141821, end_date=20250521T141822
[2025-05-21T14:18:22.987+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T14:18:23.083+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-21T14:18:23.088+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
