[2025-05-20T23:27:14.397+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T23:27:14.451+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T23:21:58.810763+00:00 [queued]>
[2025-05-20T23:27:14.480+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T23:21:58.810763+00:00 [queued]>
[2025-05-20T23:27:14.481+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-20T23:27:14.508+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_merge> on 2025-05-20 23:21:58.810763+00:00
[2025-05-20T23:27:14.527+0000] {standard_task_runner.py:72} INFO - Started process 649 to run task
[2025-05-20T23:27:14.537+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'merge_sources_pipeline', 'run_merge', 'manual__2025-05-20T23:21:58.810763+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpot_k6220']
[2025-05-20T23:27:14.544+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask run_merge
[2025-05-20T23:27:14.643+0000] {task_command.py:467} INFO - Running <TaskInstance: merge_sources_pipeline.run_merge manual__2025-05-20T23:21:58.810763+00:00 [running]> on host 0a7de9743f25
[2025-05-20T23:27:15.267+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='merge_sources_pipeline' AIRFLOW_CTX_TASK_ID='run_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T23:21:58.810763+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T23:21:58.810763+00:00'
[2025-05-20T23:27:15.270+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-20T23:27:15.322+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 56, in run_merge
    return merge_sources(flight_df, aircraft_df, airport_df).to_dict(orient="records")
  File "/opt/airflow/scripts/merge_sources.py", line 25, in merge_sources
    airport_df[["code_iata", "code_oaci"]],
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['code_iata', 'code_oaci'], dtype='object')] are in the [columns]"
[2025-05-20T23:27:15.350+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=merge_sources_pipeline, task_id=run_merge, run_id=manual__2025-05-20T23:21:58.810763+00:00, execution_date=20250520T232158, start_date=20250520T232714, end_date=20250520T232715
[2025-05-20T23:27:15.406+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-20T23:27:15.407+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task run_merge ("None of [Index(['code_iata', 'code_oaci'], dtype='object')] are in the [columns]"; 649)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/inference_dag.py", line 56, in run_merge
    return merge_sources(flight_df, aircraft_df, airport_df).to_dict(orient="records")
  File "/opt/airflow/scripts/merge_sources.py", line 25, in merge_sources
    airport_df[["code_iata", "code_oaci"]],
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['code_iata', 'code_oaci'], dtype='object')] are in the [columns]"
[2025-05-20T23:27:15.475+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T23:27:15.541+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:27:15.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
