[2025-05-21T12:25:25.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T12:25:25.963+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T12:25:21.841644+00:00 [queued]>
[2025-05-21T12:25:25.981+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T12:25:21.841644+00:00 [queued]>
[2025-05-21T12:25:25.982+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-21T12:25:26.010+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_flight_file> on 2025-05-21 12:25:21.841644+00:00
[2025-05-21T12:25:26.030+0000] {standard_task_runner.py:72} INFO - Started process 697 to run task
[2025-05-21T12:25:26.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'contrails_prediction_pipeline', 'wait_for_flight_file', 'manual__2025-05-21T12:25:21.841644+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpx8xkmanu']
[2025-05-21T12:25:26.059+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask wait_for_flight_file
[2025-05-21T12:25:26.209+0000] {task_command.py:467} INFO - Running <TaskInstance: contrails_prediction_pipeline.wait_for_flight_file manual__2025-05-21T12:25:21.841644+00:00 [running]> on host 71f2da9c2e69
[2025-05-21T12:25:26.426+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='contrails_prediction_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_flight_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T12:25:21.841644+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T12:25:21.841644+00:00'
[2025-05-21T12:25:26.430+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-21T12:25:26.435+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-05-21T12:25:26.489+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-05-21T12:25:26.490+0000] {filesystem.py:109} INFO - Poking for file /opt/***/data/raw_data/flight_2025_05.csv
[2025-05-21T12:25:26.540+0000] {taskinstance.py:310} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-05-21T12:25:26.541+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-21T12:25:26.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T12:25:26.664+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T12:25:26.668+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
